### PR TITLE
WIP: Fix workflow

### PR DESCRIPTION
**Pull request by matiasalbarello**

### CODE REVIEW

**Comment by matiasalbarello** [comment]
Apparently, there was an error on the yml file for the `allowed-conclusions` input

**Comment by progapandist** [comment]
Cool, feel free to merge

**Review by Billy- — APPROVED** [review]

**Comment by Billy-** [comment]
I should probably amend https://github.com/lewagon/wait-on-check-action/pull/20/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R32 on my pr to match, right? i.e no quotes.

My editor (VSCode, with Red Hat YAML plugin) is complaining that this line is even an array, saying it should be a string.. I am assuming that is an issue my end, but I don't have intellisense on this.

**Comment by matiasalbarello** [comment]
Don't merge this PR. Is still not solving the issue. Check at my comment on the other PR

**Pull request closed without merging**
