### PR TITLE
Use octokit gem to use GitHub API

### PR DESCRIPTION
**Pull request by matiasalbarello**
Introduce Octokit as an interface with the GitHub API. This will allow us to have more flexibility in upcoming features.

### CODE REVIEW

**Comment by progapandist** [comment]
Nice one! Can you also take a look at the issue I mentioned you in?

**Comment by matiasalbarello** [comment]
@progapandist  [this](https://github.com/lewagon/wait-on-check-action/issues/13) should be fixed now

**Comment by progapandist** [comment]
I'm ready to merge it and see what breaks 😆 you?

**Comment by matiasalbarello** [comment]
go ahead. There are still more features to come 😅

**Pull request merged**
