### PR TITLE
feat: add allow_skipped option

### PR DESCRIPTION
**Pull request by Billy-**
RE #12 

I've done the easy bit, but I'm not sure on a couple things:

- How/where to default the param to true
- How to add tests where the allow_skipped is non-default

Also, I don't know how to run the tests, so not sure if what I changed passes (they definitely shouldn't pass until the param is defaulted to true, as they are assuming that)!

### CODE REVIEW

**Comment by progapandist** [comment]
Thank you for the contribution! I will take a look in a next couple of days

**Comment by progapandist** [comment]
Do you mind if I check out this branch, update it with the recent master (has a lot of changes, like using `octokit` ruby client), and so some commits to test your approach out?

**Comment by AraHaan** [comment]
@progapandist oh by the way I need some help but I found out how one can basically wrap ruby with js so then we can nuke the need to use docker containers so then we could then run actions line these on Windows, Linux and the macos-latest images on github actions.

**Comment by Billy-** [comment]
@progapandist yes, please feel free! 🙂

**Comment by Billy-** [comment]
> @progapandist so then we can nuke the need to use docker containers so then we could then run actions line these on Windows, Linux and the macos-latest images on github actions.

One of the benefits of Docker is running on any platform without needing any pre-requisites?

Maybe something to open a new issue to discuss - not sure if it's directly related to this PR?

**Comment by progapandist** [comment]
Yeah, I will definitely not nuke Docker :) Wrapping Ruby in JS sounds horrible, though I'm open to reading more about that. The problem with Docker right now is that inly Ubuntu runners of GitHub support it, but I'm sure it's bound to change.

**Comment by matiasalbarello** [comment]
May I suggest for this feature to not only limit it for checks completed with `skipped` conclusion? We can make it more flexible so the user decides if for example a canceled or timed-out check count or not. The option could be `allowed_conclusions` or similar. What do you think?

**Comment by Billy-** [comment]
> May I suggest for this feature to not only limit it for checks completed with `skipped` conclusion? We can make it more flexible so the user decides if for example a canceled or timed-out check count or not. The option could be `allowed_conclusions` or similar. What do you think?

Great idea 😎 I have created an alternate PR #20

**Pull request closed without merging**
