### PR TITLE
Feature/add tests

### PR DESCRIPTION
**Pull request by matiasalbarello**
Since I'm using this Action and I'd like to make it less prompt to errors (like I did myself in the last PR, with a simple typo), I think it would be great to include some tests.

This PR includes some basic configurations and tests. I'm actually working on a refactor to make the script easier to read and change, but I'd like to have this base.

I was using a couple of workflows as an "end to end" way of testing. I can keep them for myself or you can adapt them to your needs. I found them useful. There are also some scripts to easily trigger those workflows.

### CODE REVIEW

**Comment by progapandist** [comment]
Amazing work! Can we also add workflow-dispatch triggers (https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch) to easily trigger test workflows through UI?

**Comment by matiasalbarello** [comment]
Definitely. I tried to implement a workflow that would trigger the rest of them but then I realized that it's only possible using a personal access token. Then I implemented the small bash script. 
The workflow_dispatch makes half of the job since you would need to lunch the other "simple tasks" first. I could add a delay step for those dummy checks so they give time to manually trigger those who wait. Does it make sense?

**Comment by progapandist** [comment]
kind of makes sense! let's try that :)

**Comment by progapandist** [comment]
Amazing! Really, really appreciate your initiative and love for clean testing. The final step would be an action that runs rspec on each `push` and `pull_request`, and a status badge for that in README. Also, maybe explain the testing flow in README too (not for Ruby tests, for action tests). Then I'll happily merge and bump the release to a minor version.

**Comment by progapandist** [comment]
Can you plz explain a bit how you use `trigger-scripts`. This is something novel to me and I'd like to learn

**Comment by matiasalbarello** [comment]
Sure! Soon I'll update the readme with more instructions. 
About the trigger scripts, is to be used in your local computer since if you execute it in a workflow, it would not have the expected result (triggering other workflows). It assumes you have this repo as your 'origin' remote. The script is simple: it creates a tag in the remote repo. The test-workflows are configured to be triggered when you push tags starting with a certain name (the name of the test). To keep the tags "clean", the workflows delete them after they're executed.

**Comment by progapandist** [comment]
Is it ready to be merged yet, or you'll give me a shout?

**Comment by matiasalbarello** [comment]
Sorry for the delay. I've updated the README. Please have a look and let me know if you see anything to improve. English is not my first language and I may have mistakes 😅

**Comment by progapandist** [comment]
Great! I’ll get back to it after the weekend

**Comment by progapandist** [comment]
Trying to test your work locally (again, thank you, this is amazing), but running into an issue: 

image

What am I missing here?

**Comment by matiasalbarello** [comment]
I think is because you called the script from the project root directory.  Please try `cd .github/trigger-scripts` and then `./trigger-test-workflows.sh`. We can also fix it to make it "callable" from anywhere in the project.

**Comment by progapandist** [comment]
Oh what a beautiful language you are, bash! This is not the first time I’m facepalming with scripts. Gonna take another day to dig some more.

**Comment by matiasalbarello** [comment]
I have some other features waiting for this to get merged

**Comment by progapandist** [comment]
All right, YOLO! :)

**Pull request merged**
