### PR TITLE
[WIP] Testing tests

### PR DESCRIPTION
**Pull request by progapandist**
Let's see how the tests run

### CODE REVIEW

**Comment by matiasalbarello** [comment]
One of the blockers I found testing the workflows is that in the "Wait omitting check-name", it's actually waiting for the other test workflows because they're all related with the same commit. Which would make it fail if another test fails (false negative). 
And the problem is that re-running the jobs would not discard the results of the previous jobs, and would fail again.

**Comment by progapandist** [comment]
I have no problem with false negatives — if one of the tests fail it means PR can't be merged :)

**Comment by matiasalbarello** [comment]
yeah.. but if a previous fail was because a 3rd party dependency and it was fixed, you need to make an "empty" commit to set a fresh ref base

**Comment by matiasalbarello** [comment]
and nobody likes flaky tests, but they're rather common 😅

**Comment by progapandist** [comment]
The goal is not to have too many dependencies you know :) I actually wrote it as a single Ruby script on purpose. Adding octokit made the tool like 10 times larger, but I'm fine with that because of your work. I don't want any other dependencies though

**Comment by progapandist** [comment]
Empty commits are fine too. Plus you can always rebase and force-push the PR branch

**Comment by matiasalbarello** [comment]
what if given two or more checks runs from the same check, it would only consider the latest?

**Comment by progapandist** [comment]
Then it's the problem with `omitting-check-name`, that option is for people who want to wait for all the checks to pass. If that doesn't work like that — we need to either drop a feature or make sure it does. It's actually not my use case on any of my projects currently, so up to you if you want to investigate.

**Comment by progapandist** [comment]
Basically, the purpose of this action to make sure a workflow will wait for another workflow. Waiting for ALL OTHER workflows doesn't make a lot of sense to me, but why not — if it's a valid use case. I prefer to be explicit and just run the action three times if you wait for three workflows

**Comment by progapandist** [comment]
In terms of how we test it — it's imperative that we just run one longer-running task and then wait for it in different flavors of your action. As this is how people will use it too.

**Comment by matiasalbarello** [comment]
I'm just thinking of a scenario where you for example have these workflows triggered on PR closed & merged:
- Some integration test workflow -> it may have a flaky test or 3rd party dependency, which would require re-run it some times
- Some other workflows
- Deploy workflow: it would wait for all tasks to finish and then deploy. 
If tests fail, for instance, and it was just because some other system was down and they just need to re-run the job, the deploy waiting task would never succeed due to the first fail. They would need the empty commit to have the fresh base (which is not that bad but is an extra step).
I would not drop the feature but instead, add some documentation about it, that it's expected behavior and not a bug.

**Comment by progapandist** [comment]
So you've been talking about the end-user experience with the action, not the way we just setup tests for ourselves? If so, I'm sorry for confusion. Of course, feel free to test and add the line to the docs. Hard for me to wrap my head over it until I actually use it like that :)

**Comment by matiasalbarello** [comment]
I'm probably mixing the end-user experience and our tests, but actually, our scenario has a "next level" complexity since it is testing itself. For now, an empty commit is fine, since it is not involving deploys or similar. But for the future (and this includes improving end-user experience) I'd suggest adding an "ignore old executions" flag as input to complement the feature of omitting the check-name

**Comment by progapandist** [comment]
I think we should cross that bridge when we come to it :)

**Pull request closed without merging**
