### PR TITLE
Bump per_page parameter to 100 in check_runs_for_ref call.

### PR DESCRIPTION
**Pull request by ditman**
This passes the `per_page` parameter to the `check_runs_for_ref` octokit request.

* Mitigates https://github.com/lewagon/wait-on-check-action/issues/40

(Apologies for the poor quality of this PR, I *think* I have a somewhat working testing environment, but I don't know much about ruby or how to contribute properly. All I could do was run the tests and see them pass (?)):

```
➜  app git:(bump-per-page-to-100) ✗ bundle exec rspec
......[#<OpenStruct status="in_progress", conclusion=nil, name="invoking_check">, #<OpenStruct status="completed", conclusion="success", name="check_completed_success">, #<OpenStruct status="completed", conclusion="failure", name="check_completed_failure">, #<OpenStruct status="completed", conclusion="neutral", name="check_completed_neutral">, #<OpenStruct status="completed", conclusion="timed_out", name="check_completed_timed_out">, #<OpenStruct status="completed", conclusion="action_required", name="check_completed_action_required">, #<OpenStruct status="queued", conclusion=nil, name="action_queued">]
...........

Finished in 0.03195 seconds (files took 0.43465 seconds to load)
17 examples, 0 failures
```

(I know this is very basic ruby, but I'm not even sure how to add a test to assert that we're calling the octokit client with the expected `per_page: 100` value!)

### CODE REVIEW

**Comment by progapandist** [comment]
cc @matiasalbarello / @JoelLefkowitz — can one of you please take a look and maybe craft a new release with all recent changes? master is now veeeery different from the latest release. you should both have full access, as I'm leaving Le Wagon and won't be able to maintain this repo for a while. Hope you can pick up the banner! ❤️

**Comment by matiasalbarello** [comment]
Hi @ditman. Thanks for the PR. 
I was taking a read to the documentation from Octokit and found [this issue](https://github.com/octokit/octokit.rb/issues/1215) (which is not actually an issue but just a request to improve their documentation). Long story short: I don't think we need to add the `per_page` option but rather setting `auto_paginate` true on the client instance creation  (`entrypoint.rb` file). It's a rather simple change, would you like to add it?

**Review by matiasalbarello — APPROVED** [review]
> @matiasalbarello would it be possible to temporarily set the `per_page` parameter to 100, until the Octokit client supports the `auto_paginate` option for the check_runs_for_ref API method properly? (See [this PR](https://github.com/octokit/octokit.rb/pull/1321)).

Of course! I did some tests [here](https://github.com/lewagon/wait-on-check-action/pull/44) with >40 workflows and worked. So I'd say it's good to go. Thanks!

**Comment by matiasalbarello** [comment]
I just merged master and fixed a little conflict.

**Pull request merged**
